// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using anskus.Infrastructure.Data;

#nullable disable

namespace anskus.Infrastructure.Migrations
{
    [DbContext(typeof(TestAnskusContext))]
    [Migration("20240521030242_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("anskus.Domain.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdImagenPerfil")
                        .HasColumnType("int")
                        .HasColumnName("id_imagen_perfil");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex(new[] { "IdImagenPerfil" }, "IX_AspNetUsers_id_imagen_perfil");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("anskus.Domain.Entity.Authentication.RefreshToken", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Categoria1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoria");

                    b.HasKey("IdCategoria")
                        .HasName("PK__categori__8A3D240C8F6227BC");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Cuestionario", b =>
                {
                    b.Property<int>("IdCuestionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuestionario"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Publico")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasDefaultValue("title");

                    b.HasKey("IdCuestionario")
                        .HasName("PK__cuestion__4A5CFD1B822640FC");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.CuestionarioActivo", b =>
                {
                    b.Property<int>("IdCuestionario")
                        .HasColumnType("int")
                        .HasColumnName("id_cuestionario");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCuestionario");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[IdUsuario] IS NOT NULL");

                    b.HasIndex(new[] { "Codigo" }, "IX_cuestionarioActivo")
                        .IsUnique();

                    b.ToTable("cuestionarioActivo");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.ImagenesPerfil", b =>
                {
                    b.Property<int>("IdImagen")
                        .HasColumnType("int")
                        .HasColumnName("id_imagen");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen");

                    b.HasKey("IdImagen")
                        .HasName("PK__imagenes__27CC26894DE81741");

                    b.ToTable("imagenes_perfil");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Pregunta", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pregunta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPregunta"));

                    b.Property<int>("IdCuestionario")
                        .HasColumnType("int");

                    b.Property<string>("pregunta")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("pregunta");

                    b.HasKey("IdPregunta")
                        .HasName("PK__pregunta__6867FFA45AFDA0E8");

                    b.HasIndex(new[] { "IdCuestionario" }, "IX_preguntas_id_cuestionario");

                    b.ToTable("preguntas");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Respuesta", b =>
                {
                    b.Property<int>("IdRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_respuesta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRespuesta"));

                    b.Property<int>("IdPregunta")
                        .HasColumnType("int")
                        .HasColumnName("id_pregunta");

                    b.Property<bool>("RCorrecta")
                        .HasColumnType("bit")
                        .HasColumnName("R_correcta");

                    b.Property<string>("respuesta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("respuesta");

                    b.HasKey("IdRespuesta")
                        .HasName("PK__respuest__14E55589836F7548");

                    b.HasIndex(new[] { "IdPregunta" }, "IX_respuestas_id_pregunta");

                    b.ToTable("respuestas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("anskus.Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("anskus.Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("anskus.Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("anskus.Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("anskus.Domain.Authentication.ApplicationUser", b =>
                {
                    b.HasOne("anskus.Domain.Models.dbModels.ImagenesPerfil", "IdImagenPerfilNavigation")
                        .WithMany()
                        .HasForeignKey("IdImagenPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdImagenPerfilNavigation");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Cuestionario", b =>
                {
                    b.HasOne("anskus.Domain.Models.dbModels.Categoria", "IdCategoriaNavigation")
                        .WithMany("Cuestionarios")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cuestionario_categoria");

                    b.HasOne("anskus.Domain.Authentication.ApplicationUser", "IdUsuarioNavigation")
                        .WithMany("Cuestionario")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_cuestionario_usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.CuestionarioActivo", b =>
                {
                    b.HasOne("anskus.Domain.Models.dbModels.Cuestionario", "IdCuestionarioNavigation")
                        .WithOne("CuestionarioActivo")
                        .HasForeignKey("anskus.Domain.Models.dbModels.CuestionarioActivo", "IdCuestionario")
                        .IsRequired()
                        .HasConstraintName("FK_CuestionarioA_cuestionario");

                    b.HasOne("anskus.Domain.Authentication.ApplicationUser", "IdUsuarioNavigation")
                        .WithOne("CuestionarioActivo")
                        .HasForeignKey("anskus.Domain.Models.dbModels.CuestionarioActivo", "IdUsuario")
                        .HasConstraintName("FK_cuestionarioActivo_usuarios");

                    b.Navigation("IdCuestionarioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Pregunta", b =>
                {
                    b.HasOne("anskus.Domain.Models.dbModels.Cuestionario", "cuestionario")
                        .WithMany("Pregunta")
                        .HasForeignKey("IdCuestionario")
                        .IsRequired()
                        .HasConstraintName("FK_preguntas_cuestionario");

                    b.Navigation("cuestionario");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Respuesta", b =>
                {
                    b.HasOne("anskus.Domain.Models.dbModels.Pregunta", "IdPreguntaNavigation")
                        .WithMany("Respuesta")
                        .HasForeignKey("IdPregunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_respuesta_pregunta");

                    b.Navigation("IdPreguntaNavigation");
                });

            modelBuilder.Entity("anskus.Domain.Authentication.ApplicationUser", b =>
                {
                    b.Navigation("Cuestionario");

                    b.Navigation("CuestionarioActivo");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Categoria", b =>
                {
                    b.Navigation("Cuestionarios");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Cuestionario", b =>
                {
                    b.Navigation("CuestionarioActivo");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("anskus.Domain.Models.dbModels.Pregunta", b =>
                {
                    b.Navigation("Respuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
